# Generated by Django 4.2.2 on 2023-06-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fill_TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(verbose_name='Код', max_length=50)),
                ('utask', models.TextField(verbose_name='Задача')),
                ('uname', models.CharField(max_length=100, verbose_name='Исполнитель')),
            ],
        ),
    ]
