# Generated by Django 4.2.2 on 2023-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uCodeIS', models.CharField(max_length=100, verbose_name='Код ИС')),
                ('uFullName', models.TextField(verbose_name='Полное наименование')),
                ('uOrgCode', models.CharField(max_length=100, verbose_name='Код Организации')),
            ],
        ),
    ]
