# Generated by Django 4.2.2 on 2023-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uShortName', models.CharField(max_length=100, verbose_name='Короткое название')),
                ('uLongName', models.TextField(verbose_name='Полное название')),
                ('uSystem', models.CharField(max_length=100, verbose_name='Система')),
                ('uCodePackage', models.CharField(max_length=100, verbose_name='Код Package')),
                ('uModulesID', models.CharField(max_length=50, verbose_name='id')),
                ('uConstruction', models.CharField(max_length=100, verbose_name='Construction')),
                ('uStage', models.CharField(max_length=100, verbose_name='Stage')),
            ],
        ),
    ]
