# Generated by Django 4.2.2 on 2023-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.CharField(max_length=50, verbose_name='Код')),
                ('uType', models.CharField(max_length=100, verbose_name='Type')),
                ('uComponentA', models.CharField(max_length=100, verbose_name='Component A')),
                ('uComponentB', models.CharField(max_length=100, verbose_name='Component B')),
                ('uLinkedProducts', models.CharField(max_length=100, verbose_name='LinkedProducts')),
                ('uName', models.TextField(verbose_name='Название')),
                ('uStatus', models.CharField(max_length=100, verbose_name='Статус')),
                ('uComand', models.CharField(max_length=100, verbose_name='Команда')),
                ('uRP', models.CharField(max_length=100, verbose_name='РП')),
                ('uStartTime', models.DateField(verbose_name='Дата начала')),
                ('uStopTime', models.DateField(verbose_name='Дата окончания')),
                ('uCustomer', models.CharField(max_length=100, verbose_name='Заказчик')),
                ('uNotes', models.TextField(verbose_name='Notes')),
                ('uDocumentation', models.URLField(verbose_name='Документация')),
                ('uConstruction', models.CharField(max_length=100, verbose_name='Construction')),
                ('uAncestor', models.CharField(max_length=50, verbose_name='Предок')),
                ('uLinkProject', models.URLField(verbose_name='LinkProject')),
            ],
        ),
    ]
