# Generated by Django 4.2.2 on 2023-07-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_uconstruction_modules_umodulesconstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uArchID', models.CharField(max_length=50, verbose_name='Код')),
                ('uSys_A', models.CharField(max_length=100, verbose_name='sys_A')),
                ('uArchLink', models.CharField(max_length=100, verbose_name='link')),
                ('uSys_B', models.CharField(max_length=100, verbose_name='sys_B')),
            ],
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='uModulesConstruction',
            new_name='uConstruction',
        ),
    ]
