# Generated by Django 4.2.2 on 2023-07-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_archlayout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uVehID', models.CharField(max_length=50, verbose_name='ID')),
                ('uVehDate', models.DateField(verbose_name='Date')),
                ('uVehProductID', models.CharField(max_length=50, verbose_name='ProductID')),
                ('uVehType', models.CharField(max_length=100, verbose_name='Type')),
                ('uVehDescription', models.TextField(verbose_name='Description')),
                ('uVehBaseDoc', models.TextField(verbose_name='Документ основания')),
                ('uVehSubmDoc', models.TextField(verbose_name='Подтверждающий документ')),
                ('uVehPriority', models.CharField(max_length=100, verbose_name='Priority')),
                ('uVehClosed', models.BooleanField(verbose_name='Closed')),
            ],
        ),
    ]
