# Generated by Django 4.2.2 on 2023-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productsvnedr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uResID', models.CharField(max_length=50, verbose_name='Код')),
                ('uResName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('uResRole', models.CharField(max_length=100, verbose_name='Роль в проекте')),
                ('uResLeader', models.BooleanField(verbose_name='Лидер')),
                ('uResComand', models.CharField(max_length=200, verbose_name='Команда')),
                ('uResCheck', models.CharField(max_length=100, verbose_name='Статус')),
                ('uResReport', models.CharField(max_length=100, verbose_name='Репорт')),
            ],
        ),
    ]
