# Generated by Django 4.2.2 on 2023-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uStartTime',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='products',
            name='uStopTime',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
