# Generated by Django 4.2.2 on 2023-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_products_ustarttime_alter_products_ustoptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsvnedr',
            name='uVnedrStartTime',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='productsvnedr',
            name='uVnedrStopTime',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание'),
        ),
    ]
