# Generated by Django 4.2.2 on 2023-07-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_productsvnedr_uvnedrstarttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsveh',
            name='uVehDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
