# Generated by Django 4.2.2 on 2023-07-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productsveh_uvehdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uDateReport', models.DateTimeField(verbose_name='Дата')),
                ('uIDProductReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.products')),
                ('uIDVehReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.productsveh')),
            ],
        ),
    ]
