# Generated by Django 4.2.2 on 2023-07-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='uDateReport',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.report')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
