# Generated by Django 4.2.2 on 2023-07-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_reportcomments_remove_report_uidproductreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomments',
            name='uProductIDReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='reportcomments',
            name='uVehIDReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.productsveh', verbose_name='Веха'),
        ),
    ]
