# Generated by Django 4.2.2 on 2023-07-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_reportcomments_uproductidreport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportComments',
            new_name='ReportComment',
        ),
    ]
