# Generated by Django 4.2.2 on 2023-07-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_reportcomments_reportcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCommentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('uProductIDReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.products', verbose_name='Продукт')),
                ('uVehIDReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.productsveh', verbose_name='Веха')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
